Adventureworks:
  target: windows_authentication
  outputs:
    sql_authentication:
      type: sqlserver
      driver: 'ODBC Driver 17 for SQL Server' # (The ODBC Driver installed on your system)
      server: localhost
      port: 1433
      database: DV_Demo
      schema: dbo
      user: sa
      password: P@ssw0rd
      trust_cert: TRUE
      threads: 5
      
    windows_authentication:
      type: sqlserver
      driver: 'ODBC Driver 17 for SQL Server' # (The ODBC Driver installed on your system)
      server: localhost
      port: 1433
      database: DV_Demo
      schema: dbo
      windows_login: True
      trust_cert: TRUE
      threads: 5