{{ config(materialized='view') }}
SELECT  [Customer Code]
      ,[Customer name]
      ,[Customer Channel type]
      ,[ Customer coordinates X ]
      ,[ Customer coordinates y ]
      ,[Number of Doors]
      ,[Route]
      ,[Rep name]
      ,[Supervisor name]
      ,[Service Channel]
      ,[Depot]
      ,[USM name]
      ,[Region]
      ,[RSM]
      ,[Discount]
  FROM [DV_Demo].[dbo].[Customers_DB_1]